import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {commerceAdapter,commerceIds} from '../server/commerce.mjs';
import {commerceProducts,commerceProduct,productLinkAllowed} from '../dist/commerce-catalog.js';
import {amazonChatReply} from '../server/amazon.mjs';
import {createCloudHandler} from '../cloud/backend.mjs';
import {createAmazonRunner} from '../server/amazon-run.mjs';
import {ecommercePage,amazonPage} from '../dist/amazon.js';
const ids={shein:'gd_mkv55s1f23yjzsl4ix',walmart:'gd_l95fol7l1ru6rlo116',ebay:'gd_ltr9mjt81n0zzdk1fb',etsy:'gd_ltppk0jdv1jqz25mz',aliexpress:'gd_mlj9v75u1w1jvaxvwp',target:'gd_ltppk5mx2lp0v1k0vo',bestbuy:'gd_ltre1jqe1jfr7cccf'};
const env={PUBLIC_ORIGIN:'https://market.example.com',SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'publishable-fixture',BRIGHT_DATA_API_KEY:'fixture',ANTHROPIC_API_KEY:'fixture-ai',AFFSIWEN_AMAZON_CHAT_ENABLED:'yes',AFFSIWEN_AMAZON_CHAT_MODEL:'claude-haiku-4-5-20251001',AFFSIWEN_AMAZON_CHAT_DAILY_LIMIT:'2',AFFSIWEN_AMAZON_RUN_ENABLED:'yes',AFFSIWEN_AMAZON_RUNS_PER_DAY:'2'};
function metadata(id){return [{id:ids[id],scrapers:Object.fromEntries(commerceAdapter(id).tasks.filter(t=>t.family==='products').map(t=>[t.method,{input_schema:[{name:t.id==='search'?(id==='walmart'?'keyword':'keywords'):t.id==='upc'?'upc':t.id==='sku'?'sku':'url',required:true},...(id==='walmart'?[{name:'domain'}]:[]),{name:'all_variations'},{name:'zipcode'}]}]))}];}
const sample=id=>({task:['shein','aliexpress'].includes(id)?'products':'search',market:'US',limit:5,request:'Исследовать предложения',value:id==='shein'?'https://us.shein.com/dress-p-123.html':id==='aliexpress'?'https://www.aliexpress.us/item/123.html':'wireless headphones'});
async function call(path,{data,cookie='',fetcher}={}){const req=Readable.from(data===undefined?[]:[Buffer.from(JSON.stringify(data))]);req.url=path;req.method=data===undefined?'GET':'POST';req.headers={origin:env.PUBLIC_ORIGIN,'content-type':'application/json','x-affsiwen-request':'1',cookie};const out={statusCode:200,headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},end(v){this.body=v;}};await createCloudHandler({env,fetcher})(req,out);return {...out,json:()=>JSON.parse(out.body)};}
function fixture(){const docs=new Map(),posts=[];let aiCalls=0;const read=async c=>structuredClone(docs.get(c)||{revision:0,document:null});const write=async(c,document,revision)=>{const old=await read(c);if(old.revision!==revision){const e=Error('revision');e.status=409;throw e;}const saved={document:structuredClone(document),revision:revision+1};docs.set(c,saved);return structuredClone(saved);};const fetcher=async(url,opts={})=>{const u=new URL(url);if(u.hostname==='test.supabase.co'){const b=JSON.parse(opts.body);try{return Response.json(b.document===undefined?await read(b.capability):await write(b.capability,b.document,b.expected_revision));}catch{return Response.json({code:'PT409',message:'conflict'},{status:409});}}if(u.pathname.endsWith('/scrapers')){const id=commerceIds.find(id=>metadata(id)&&u.searchParams.get('domain').includes(id==='aliexpress'?'aliexpress':id));return Response.json(metadata(id));}if(u.pathname.endsWith('/trigger')){posts.push({url:u,body:JSON.parse(opts.body)});return Response.json({snapshot_id:'sd_fixture123'});}if(u.pathname.includes('/progress/'))return Response.json({status:'ready'});if(u.pathname.includes('/snapshot/'))return Response.json([{title:'Headphones',product_id:'sku42',price:25,currency:'USD',url:'https://www.ebay.com/itm/123'}]);if(u.hostname==='api.anthropic.com'){aiCalls++;const b=JSON.parse(opts.body),id=Object.keys(ids).find(id=>b.system.includes(commerceProduct(id).name))||'ebay';const p=sample(id);return Response.json({stop_reason:'tool_use',usage:{input_tokens:10,output_tokens:10},content:[{type:'tool_use',name:'amazon_assistant_reply',input:{status:'ready',message:'ready',options:[],...p,goal:p.request,imageSummary:'',zipcode:''}}]});}throw Error('Unexpected URL '+u);};return {docs,posts,read,write,fetcher,get aiCalls(){return aiCalls;}};}
for(const id of commerceIds)test(id+': live-schema adapter builds only its verified source contract',async()=>{const a=commerceAdapter(id),inv=await a.inventory({key:'fixture',fetcher:async()=>Response.json(metadata(id))});const p=a.prepare(sample(id),inv);assert.equal(p.display.product,id);assert.equal(p.contract.query.dataset_id,ids[id]);assert.equal(p.contract.body.input.length,1);assert.equal(p.contract.body.limit_per_input,5);assert.equal(p.contract.body.input[0].all_variations,false);assert.doesNotMatch(JSON.stringify(a.publicConnection(inv)),/gd_|fixture|scrapers|Bearer/);assert.throws(()=>a.prepare({...sample(id),task:'products',value:'https://evil.example/x'},inv));assert.throws(()=>a.prepare({...sample(id),market:'XX'},inv));assert.throws(()=>a.prepare({...sample(id),limit:101},inv));});
test('unsupported operations, new required fields and unsafe URLs fail closed',()=>{const a=commerceAdapter('aliexpress');assert.throws(()=>a.prepare({...sample('aliexpress'),task:'search'},{connected:true,inventory:metadata('aliexpress')}));const b=metadata('etsy');b[0].scrapers.discover_by_keywords.input_schema.push({name:'new_required_field',required:true});assert.throws(()=>commerceAdapter('etsy').prepare(sample('etsy'),{connected:true,inventory:b}),/уточнить/);for(const url of ['https://etsy.com.evil.example/x','https://etsy.com@evil.example/x','http://etsy.com/x','https://etsy.com:444/x'])assert.equal(productLinkAllowed(url,commerceProduct('etsy')),false);});
test('normalization preserves source IDs and only links to the selected store',()=>{const a=commerceAdapter('ebay'),plan={columns:['Товар','ID товара','Цена','Валюта','Ссылка'],limit:5,title:'Products'};const r=a.normalize([{title:'x',item_id:'123',price:12,url:'https://www.ebay.com/itm/123'},{title:'bad link',url:'https://www.amazon.com/dp/123'}],plan);assert.equal(r.rows[0]['ID товара'],'123');assert.equal(r.rows[0]['Цена'],'12');assert.equal(r.rows[1]['Ссылка'],'—');assert.equal(r.rows[1]['Валюта'],'—');assert.equal(r.synthetic,false);});
test('product chat schema gives the model only connected operations and markets',async()=>{const a=commerceAdapter('etsy'),inv={connected:true,inventory:metadata('etsy')};let body;const fetcher=async(url,opts)=>{body=JSON.parse(opts.body);return Response.json({stop_reason:'tool_use',content:[{type:'tool_use',name:'amazon_assistant_reply',input:{status:'ready',message:'Starting',options:[],task:'search',market:'US',limit:5,value:'ceramic cups',goal:'Compare cups',imageSummary:'',zipcode:''}}]});};const r=await amazonChatReply({messages:[{role:'user',content:'Compare 5 ceramic cups in Etsy US'}],inventory:inv,env,fetcher,adapter:a});assert.equal(r.prepared.display.product,'etsy');assert.ok(body.system.includes('Etsy'));assert.ok(!body.tools[0].input_schema.properties.task.enum.includes('reviews'));assert.deepEqual(body.tools[0].input_schema.properties.market.enum,['US',null]);assert.match(r.answer.message,/Сбор ещё не запущен/);});
test('each product has a separate persisted workspace and cloud CSV path',async()=>{const f=fixture();const prepared=await call('/api/commerce/ebay/prepare',{data:sample('ebay'),fetcher:f.fetcher});assert.equal(prepared.statusCode,200);const cookie=prepared.headers['set-cookie'][0].split(';')[0];assert.match(cookie,/^aff_commerce_ebay=/);const plan=prepared.json().plan;const other=await call('/api/commerce/etsy/workspace',{cookie,fetcher:f.fetcher});assert.equal(other.json().plan,null);const run=await call('/api/commerce/ebay/run',{data:{planId:plan.id,confirm:true},cookie,fetcher:f.fetcher});assert.equal(run.json().run.status,'running');const result=await call('/api/commerce/ebay/run/status',{cookie,fetcher:f.fetcher});assert.equal(result.json().run.result.rows[0]['ID товара'],'sku42');const csv=await call('/api/commerce/ebay/export',{cookie,fetcher:f.fetcher});assert.match(csv.headers['content-disposition'],/affsiwen-ebay.csv/);assert.match(csv.body,/Headphones/);assert.equal((await call('/api/commerce/ebay/workspace',{cookie,fetcher:f.fetcher})).json().run.status,'ready');assert.equal(f.posts.length,1);assert.equal((await call('/api/commerce/notastore/connection',{fetcher:f.fetcher})).statusCode,404);});
test('the paid-run quota is shared across stores and same-capability jobs remain separated',async()=>{const f=fixture(),cap='a'.repeat(64),id='b'.repeat(32);for(const product of ['etsy','ebay']){const r=createAmazonRunner({...f,env,adapter:commerceAdapter(product)});await r.start(cap,{...sample(product),id});}const third=createAmazonRunner({...f,env,adapter:commerceAdapter('bestbuy')});await assert.rejects(()=>third.start(cap,{...sample('bestbuy'),id}),/лимит/);assert.equal(f.posts.length,2);assert.notEqual(f.posts[0].url.searchParams.get('dataset_id'),f.posts[1].url.searchParams.get('dataset_id'));});
test('the existing AI allowance is shared across all commerce chats',async()=>{const f=fixture();for(const id of ['ebay','etsy','bestbuy']){const r=await call('/api/commerce/'+id+'/chat',{data:{message:'Find 5 headphones in US',requestId:'request-'+id},fetcher:f.fetcher});assert.equal(r.statusCode,id==='bestbuy'?429:200);}assert.equal(f.aiCalls,2);});
test('catalog and product pages route to each product without supplier leakage or wrong export links',()=>{const html=ecommercePage();assert.equal(commerceProducts.length,8);for(const p of commerceProducts){assert.ok(html.includes('#product/'+p.id));const page=amazonPage({product:p,result:{synthetic:false,title:'Data',rows:[{name:'<script>x</script>'}],requested:1,createdAt:new Date().toISOString()},connection:{assistantMode:'llm',connected:true}});assert.ok(page.includes('Ваш помощник по '+p.name));assert.ok(page.includes(p.id==='amazon'?'/api/amazon/export':'/api/commerce/'+p.id+'/export'));assert.ok(!page.includes('<script>'));if(p.id!=='amazon')assert.ok(!page.includes('Ваш помощник по Amazon'));}assert.doesNotMatch(html,/Bright Data|gd_|Apify|Actor/);});

test('URL-only product cannot suggest unsupported keyword search even if the model does',async()=>{const adapter=commerceAdapter('aliexpress');const r=await amazonChatReply({messages:[{role:'user',content:'Find 5 wireless headphones, no URL yet'}],inventory:{connected:true,inventory:metadata('aliexpress')},env,adapter,fetcher:async()=>Response.json({stop_reason:'tool_use',content:[{type:'tool_use',name:'amazon_assistant_reply',input:{status:'clarify',message:'Уточните поисковую фразу',options:['Напишите ключевые слова'],task:null,market:'US',limit:5,value:'headphones',goal:'Compare',imageSummary:'',zipcode:''}}]})});assert.match(r.answer.message,/Поиск по словам пока недоступен/);assert.deepEqual(r.answer.options,[]);assert.equal(r.state.value,null);assert.equal(r.prepared,null);});
