import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {realEstateAdapter,realEstateDefinitions} from '../server/real-estate.mjs';
import {commerceAdapter} from '../server/commerce.mjs';
import {realEstateProducts} from '../dist/commerce-catalog.js';
import {realEstatePage,amazonPage} from '../dist/amazon.js';
import {publicShell} from '../dist/landing.js';
import {amazonChatReply} from '../server/amazon.mjs';
import {createCloudHandler} from '../cloud/backend.mjs';
import {createAmazonRunner} from '../server/amazon-run.mjs';
import {HttpError} from '../server/errors.mjs';
const urls={zillow:'https://www.zillow.com/homedetails/Example/123_zpid/',otodom:'https://www.otodom.pl/pl/oferta/example-ID123',realestate:'https://www.realestate.com.au/property-house-qld-example-123',zoopla:'https://www.zoopla.co.uk/to-rent/details/123/',zonaprop:'https://www.zonaprop.com.ar/propiedades/example.html',inmuebles:'https://www.inmuebles24.com/propiedades/example.html',metrocuadrado:'https://www.metrocuadrado.com/inmueble/example',toctoc:'https://www.toctoc.com/propiedades/example',properati:'https://www.properati.com.co/s/example',infocasas:'https://www.infocasas.com.uy/example/123',suumo:'https://suumo.jp/chintai/bc_100477775592/'};
function inventory(id){const d=realEstateDefinitions[id],operations=d.operations||{property:['listing','collect_by_url']};return {connected:true,inventory:Object.entries(d.families).map(([family,id])=>({id,scrapers:Object.fromEntries(Object.entries(operations).filter(([,v])=>v[0]===family).map(([task,[,method]])=>{
 const fields=task==='search'?(d.domain==='zillow.com'?['location','listingCategory','HomeType','days_on_zillow','exact_address']:d.domain==='zoopla.co.uk'?['property_type','location']:d.domain==='suumo.jp'?['category','building_type','condominium_rental']:['filter']):method==='discover_by_url'&&d.domain==='realestate.com.au'?['url','split_property_type','split_price_range','limit_pages','days_back']:task==='searchpage'?['url','include_offmarket']:['url'];
 return [method,{input_schema:fields.map((name,i)=>({name,required:i===0||d.domain==='zoopla.co.uk'}))}];
 }))}))};}
function data(id,task='property'){return {task,market:'GLOBAL',request:'Research real estate listings',limit:5,value:task==='search'?(id==='realestate'?'rent':id==='suumo'?'rent':'London'):['searchurl','fullsearch','searchpage'].includes(task)?id==='zillow'?'https://www.zillow.com/austin-tx/':id==='realestate'?'https://www.realestate.com.au/rent/in-coomera/list-1':'https://www.zonaprop.com.ar/inmuebles.html':urls[id],estate:task==='search'?{kind:'rent'}:null};}
for(const id of Object.keys(realEstateDefinitions))test('Real Estate '+id+': all observed methods are isolated, bounded and private',async()=>{
 const adapter=commerceAdapter(id);assert.equal(adapter.product.category,'Real Estate');const inv=await adapter.inventory({key:'fixture',fetcher:async()=>Response.json([...inventory(id).inventory,{id:'gd_unknown',scrapers:{}}])});assert.equal(inv.inventory.length,Object.keys(realEstateDefinitions[id].families).length);
 for(const task of adapter.tasks){const p=adapter.prepare(data(id,task.id),inv);assert.equal(p.contract.query.dataset_id,realEstateDefinitions[id].families[task.family]);assert.equal(p.contract.body.limit_per_input,5);if(task.method.startsWith('discover_by_'))assert.equal(p.contract.query.discover_by,task.method.slice(12));assert.doesNotMatch(JSON.stringify(p.display)+JSON.stringify(adapter.publicConnection(inv)),/gd_|fixture|Bearer|dataset_id/);}
 assert.equal(adapter.available(inv).length,adapter.tasks.length);for(const value of ['https://evil.example/x','http://'+adapter.product.hosts[0]+'/x','https://'+adapter.product.hosts[0]+':444/x','https://'+adapter.product.hosts[0]+'@evil.example/x','https://'+adapter.product.hosts[0]+'/'])assert.throws(()=>adapter.prepare({...data(id),value},inv));
 const changed=structuredClone(inv);changed.inventory[0].scrapers.collect_by_url.input_schema.push({name:'unknown_required',required:true});assert.throws(()=>adapter.prepare(data(id),changed),/дополнительный/);
});
test('all 22 endpoint paths are included without inventing place filters on category-only sources',()=>{
 assert.equal(Object.keys(realEstateDefinitions).length,11);assert.equal(Object.keys(realEstateDefinitions).reduce((n,id)=>n+realEstateAdapter(id).tasks.length,0),22);
 const z=realEstateAdapter('zillow').prepare({...data('zillow','search'),value:'Austin',estate:{kind:'sale',homeType:'Houses',exactAddress:false}},inventory('zillow'));assert.deepEqual(z.contract.body.input[0],{location:'Austin',listingCategory:'House for sale',HomeType:'Houses',exact_address:false});
 const zo=realEstateAdapter('zoopla').prepare(data('zoopla','search'),inventory('zoopla'));assert.deepEqual(zo.contract.body.input[0],{property_type:'to rent',location:'London'});
 for(const id of ['zillow','zoopla','realestate','suumo'])assert.throws(()=>realEstateAdapter(id).prepare({...data(id,'search'),estate:{}},inventory(id)),/тип сделки/);
 assert.throws(()=>realEstateAdapter('realestate').prepare({...data('realestate','search'),value:'Sydney'},inventory('realestate')),/город/);
 assert.throws(()=>realEstateAdapter('suumo').prepare({...data('suumo','search'),value:'Tokyo'},inventory('suumo')),/город/);
 const au=realEstateAdapter('realestate').prepare(data('realestate','searchurl'),inventory('realestate'));assert.equal(au.contract.body.input[0].split_property_type,false);assert.equal(au.contract.body.input[0].limit_pages,1);assert.throws(()=>realEstateAdapter('realestate').prepare({...data('realestate','searchurl'),estate:{splitPropertyType:true}},inventory('realestate')),/разбиение/);
});
test('result normalization preserves source history events, zero, missing currency and property links from discovery',()=>{
 const a=realEstateAdapter('zillow'),p=a.prepare(data('zillow','history'),inventory('zillow')).display;const r=a.normalize([{url:urls.zillow,date:'2013-06-22',event:'Listed for sale',price:0,price_change_rate:0,price_per_squarefoot:435},{error:'failed'}],p);assert.equal(r.rows[0]['Цена события'],'0');assert.equal(r.rows[0]['Изменение цены, %'],'0');assert.equal(r.rows[0]['Валюта'],'—');assert.equal(r.errorRecords,1);
 const search=a.prepare(data('zillow','searchurl'),inventory('zillow')).display;const list=a.normalize([{url:urls.zillow,address:'Example',bedrooms:0,price:100,livingArea:30}],search);assert.equal(list.rows[0]['Ссылка'],urls.zillow);assert.equal(list.rows[0]['Спальни'],'0');assert.equal(list.rows[0]['Единица площади'],'—');assert.equal(list.rows[0]['Валюта'],'—');assert.equal(a.normalize([{url:'https://evil.example/x',title:'Test'}],search).rows[0]['Ссылка'],'—');
 const huge=a.normalize(Array.from({length:10},()=>({url:urls.zillow+'?x='+'x'.repeat(10000),title:'😀'.repeat(10000),address:'😀'.repeat(10000),price:'x'.repeat(10000)})),{...search,limit:10});assert.ok(Buffer.byteLength(JSON.stringify(huge))<40000);assert.equal(huge.rows[0]['Ссылка'],'—');
});
test('AI chat carries sale/rent criteria to the plan and treats Zillow history as a connected operation',async()=>{
 const adapter=realEstateAdapter('zoopla');let body;
 const result=await amazonChatReply({adapter,inventory:inventory('zoopla'),messages:[{role:'user',content:'5 rental listings London'}],env:{ANTHROPIC_API_KEY:'fixture',AFFSIWEN_AMAZON_CHAT_ENABLED:'yes',AFFSIWEN_AMAZON_CHAT_MODEL:'claude-haiku-4-5-20251001'},fetcher:async(url,opt)=>{body=JSON.parse(opt.body);return Response.json({stop_reason:'tool_use',content:[{type:'tool_use',name:'amazon_assistant_reply',input:{status:'ready',message:'ready',options:[],task:'search',value:'London',market:'GLOBAL',limit:5,estate:{kind:'rent'},goal:'Research rentals',zipcode:'',imageSummary:''}}]});}});assert.ok(body.tools[0].input_schema.properties.estate);assert.equal(result.prepared.display.estate.kind,'rent');assert.equal(result.state.estate.kind,'rent');assert.doesNotMatch(body.system,/исторические цены, продажи/);
});
test('Real Estate UI routes all products, shows filters and avoids supplier leakage',()=>{
 assert.equal(realEstateProducts.length,11);const html=realEstatePage();for(const p of realEstateProducts){assert.ok(html.includes('#product/'+p.id));const page=amazonPage({product:p,plan:realEstateAdapter(p.id).prepare(data(p.id),inventory(p.id)).display,result:{synthetic:true,title:'Fixture',rows:[{'Объект':'Fixture'}]}});assert.ok(page.includes('href="#real-estate">Real Estate /'));assert.ok(page.includes('/api/commerce/'+p.id+'/export'));}
 assert.match(publicShell(html,{active:'estate'}),/href="#real-estate" aria-current="page"/);assert.doesNotMatch(html,/Bright Data|Apify|dataset|gd_/);
 const page=amazonPage({product:realEstateProducts.find(p=>p.id==='zoopla'),plan:realEstateAdapter('zoopla').prepare(data('zoopla','search'),inventory('zoopla')).display});assert.match(page,/Сделка: аренда/);
});
test('cloud workspaces isolate all 11 products and expose availability only',async()=>{
 const docs=new Map();const env={PUBLIC_ORIGIN:'https://fixture.example',SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_PUBLISHABLE_KEY:'fixture',BRIGHT_DATA_API_KEY:'fixture'};
 const fetcher=async(url,opt)=>{if(String(url).includes('/scrapers?')){const domain=new URL(url).searchParams.get('domain'),id=Object.keys(realEstateDefinitions).find(id=>realEstateDefinitions[id].domain===domain);return Response.json(inventory(id).inventory);}const b=JSON.parse(opt.body),old=docs.get(b.capability)||{revision:0,document:null};if(b.document){assert.equal(old.revision,b.expected_revision);docs.set(b.capability,{revision:old.revision+1,document:b.document});}return Response.json(docs.get(b.capability)||old);};
 async function call(id,path,data,cookie=''){const req=Readable.from(data?[Buffer.from(JSON.stringify(data))]:[]);req.method=data?'POST':'GET';req.url='/api/commerce/'+id+'/'+path;req.headers={origin:env.PUBLIC_ORIGIN,'content-type':'application/json','x-affsiwen-request':'1',cookie};const res={headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},end(body){this.body=body;}};await createCloudHandler({env,fetcher})(req,res);return res;}
 for(const id of Object.keys(realEstateDefinitions)){const c=await call(id,'connection');assert.equal(c.statusCode,200);assert.equal(JSON.parse(c.body).connected,true);assert.equal(JSON.parse(c.body).execution.enabled,false);const p=await call(id,'prepare',data(id));assert.equal(p.statusCode,200);const cookie=p.headers['set-cookie'][0].split(';')[0];assert.match(cookie,new RegExp('aff_commerce_'+id));const restored=await call(id,'workspace',null,cookie);assert.equal(JSON.parse(restored.body).plan.id,JSON.parse(p.body).plan.id);assert.equal(JSON.parse((await call(id,'workspace')).body).plan,null);assert.doesNotMatch(restored.body,/gd_|contract|fixture/);}
});
test('bounded real-estate runner revalidates contracts, persists actual fixtures and never repeats a trigger',async()=>{
 const docs=new Map();let triggers=0;const adapter=realEstateAdapter('zillow');const read=async key=>structuredClone(docs.get(key)||{document:null,revision:0}),write=async(key,document,revision)=>{const old=docs.get(key)||{revision:0};if(old.revision!==revision)throw new HttpError(409,'Conflict');const row={document,revision:revision+1};docs.set(key,row);return structuredClone(row);};
 const fetcher=async(url,opt={})=>{if(String(url).includes('/scrapers?'))return Response.json(inventory('zillow').inventory);if(String(url).includes('/trigger?')){triggers++;assert.equal(new URL(url).searchParams.get('dataset_id'),realEstateDefinitions.zillow.families.history);assert.equal(new URL(url).searchParams.get('limit_per_input'),'5');assert.deepEqual(JSON.parse(opt.body).input,[{url:urls.zillow}]);return Response.json({snapshot_id:'sd_fixture123'});}if(String(url).includes('/progress/'))return Response.json({status:'ready'});if(String(url).includes('/snapshot/'))return Response.json([{url:urls.zillow,date:'2026-01-01',event:'Price change',price:125000}]);throw Error('unexpected');};
 const runner=createAmazonRunner({env:{BRIGHT_DATA_API_KEY:'fixture',AFFSIWEN_AMAZON_RUN_ENABLED:'yes',AFFSIWEN_AMAZON_RUNS_PER_DAY:'1'},read,write,fetcher,adapter}),cap='a'.repeat(64),plan={...data('zillow','history'),id:'b'.repeat(32),contract:{query:{dataset_id:'forged'}}};await runner.start(cap,plan);await runner.start(cap,plan);const result=await runner.status(cap,plan.id);assert.equal(result.status,'ready');assert.equal(result.result.synthetic,false);assert.equal(result.result.rows[0]['Цена события'],'125000');assert.equal(triggers,1);assert.doesNotMatch(JSON.stringify(result),/gd_|fixture|snapshot|forged/);
});
