import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {travelAdapter,validateTravel} from '../server/travel.mjs';
import {travelProducts,commerceProduct} from '../dist/commerce-catalog.js';
import {commerceAdapter} from '../server/commerce.mjs';
import {amazonChatReply} from '../server/amazon.mjs';
import {travelPage,amazonPage} from '../dist/amazon.js';
import {createCloudHandler} from '../cloud/backend.mjs';
const ids={booking:['gd_m5mbdl081229ln6t4a','gd_mdy9ld3p1e0oqlj9g4'],airbnb:['gd_ld7ll037kqy322v05'],agoda:['gd_m837ssst155rq3a1xo'],trip:['gd_mb7q8vuuej1nso8j2'],naver:['gd_mmt7ee9m1r245mjv0v']};
const urls={booking:'https://www.booking.com/hotel/es/example.html',airbnb:'https://www.airbnb.com/rooms/123',agoda:'https://www.agoda.com/example/hotel/city.html',trip:'https://us.trip.com/hotels/detail/?hotelId=123',naver:'https://hotels.naver.com/accommodation/search/detail/domestic/123'};
const travel={checkIn:'2099-11-10',checkOut:'2099-11-12',adults:2,children:0,infants:0,pets:0,rooms:1,currency:'EUR'};
function inventory(id){const schemas=ids[id].map(id=>({id,scrapers:{collect_by_url:{input_schema:[{name:'url',required:true}]}}}));if(id==='booking'||id==='airbnb'){const fields=id==='booking'?['url','location','check_in','check_out','adults','rooms','currency']:['location','check_in','check_out','num_of_adults','num_of_children','num_of_infants','num_of_pets','currency'];schemas.at(-1).scrapers['discover_by_'+(id==='booking'?'search_input':'location')]={input_schema:fields.map(name=>({name,required:true}))};}return {connected:true,inventory:schemas};}
const plan=id=>({task:'property',market:'GLOBAL',limit:5,request:'Исследовать объект',value:urls[id]});
const env={PUBLIC_ORIGIN:'https://test.example',SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'fixture',BRIGHT_DATA_API_KEY:'fixture-source',ANTHROPIC_API_KEY:'fixture-model',AFFSIWEN_AMAZON_CHAT_ENABLED:'yes',AFFSIWEN_AMAZON_CHAT_MODEL:'claude-haiku-4-5-20251001'};
for(const id of Object.keys(ids))test('Travel '+id+': verified URL contract, namespace and public output',async()=>{const a=commerceAdapter(id);assert.equal(a.product.category,'Travel');let called;const inv=await a.inventory({key:'fixture',fetcher:async url=>{called=url;return Response.json(inventory(id).inventory);}});assert.match(called,/datasets\/v3\/scrapers\?domain=/);const p=a.prepare(plan(id),inv);assert.equal(p.contract.query.dataset_id,ids[id][0]);assert.equal(p.contract.body.input[0].url,urls[id]);assert.equal(p.contract.body.limit_per_input,5);assert.doesNotMatch(JSON.stringify(a.publicConnection(inv)),/gd_|fixture/);assert.throws(()=>a.prepare({...plan(id),value:'https://evil.example/property'},inv));assert.throws(()=>a.prepare({...plan(id),value:'https://'+a.product.hosts[0]+'/'},inv));const changed=structuredClone(inv);changed.inventory[0].scrapers.collect_by_url.input_schema.push({name:'unknown_required',required:true});assert.throws(()=>a.prepare(plan(id),changed),/дополнительные/);});
test('Travel search keeps agreed dates, guests and currency in both request and saved plan',()=>{for(const id of ['booking','airbnb']){const p=travelAdapter(id).prepare({...plan(id),task:'search',value:'Barcelona, Spain',travel},inventory(id));const input=p.contract.body.input[0];assert.equal(input.check_in,'2099-11-10T00:00:00.000Z');assert.equal(input.currency,'EUR');assert.equal(input[id==='booking'?'adults':'num_of_adults'],2);assert.equal(p.display.travel.checkOut,travel.checkOut);assert.equal(p.contract.query.discover_by,id==='booking'?'search_input':'location');}});
test('Travel rejects invalid dates, missing guests, unsupplied currency and unsupported child booking',()=>{for(const bad of [{checkIn:'2020-01-01'},{checkOut:'2099-11-09'},{checkIn:'2099-02-30'},{adults:0},{adults:'2'},{currency:''},{rooms:null},{children:1}])assert.throws(()=>validateTravel({...travel,...bad},'booking'));const p=travelAdapter('agoda');assert.throws(()=>p.prepare({...plan('agoda'),task:'search',travel},inventory('agoda')));});
test('Travel normalizer never fabricates currency, a price basis or links to another platform',()=>{const a=travelAdapter('booking'),p=a.prepare(plan('booking'),inventory('booking')).display;const r=a.normalize([{hotel_name:'Example',price:80,url:urls.booking},{hotel_name:'Other',total_price:250,currency:'EUR',url:'https://evil.example'},{error:'blocked'}],p);assert.equal(r.rows[0]['Валюта'],'—');assert.equal(r.rows[0]['Основание цены'],'—');assert.equal(r.rows[1]['Основание цены'],'Итого (поле источника)');assert.equal(r.rows[1]['Ссылка'],'—');assert.equal(r.errorRecords,1);assert.equal(r.synthetic,false);});
test('Travel chat carries dates through model schema, plan and persisted state',async()=>{const adapter=travelAdapter('booking');let body;const r=await amazonChatReply({messages:[{role:'user',content:'5 hotels Barcelona, 2099-11-10 to 2099-11-12, 2 adults, no children or infants, one room, EUR'}],inventory:inventory('booking'),env,adapter,fetcher:async(url,opt)=>{body=JSON.parse(opt.body);return Response.json({stop_reason:'tool_use',content:[{type:'tool_use',name:'amazon_assistant_reply',input:{status:'ready',message:'Ready',options:[],task:'search',market:'GLOBAL',value:'Barcelona',limit:5,travel,goal:'Compare hotels',zipcode:'',imageSummary:''}}]});}});assert.ok(body.tools[0].input_schema.properties.travel);assert.equal(r.prepared.display.travel.currency,'EUR');assert.deepEqual(r.state.travel,travel);assert.match(r.answer.message,/ещё не запущен/);});
test('Travel URL-only assistant does not offer keyword search',async()=>{const r=await amazonChatReply({messages:[{role:'user',content:'Hotels in Seoul'}],inventory:inventory('naver'),env,adapter:travelAdapter('naver'),fetcher:async()=>Response.json({stop_reason:'tool_use',content:[{type:'tool_use',name:'amazon_assistant_reply',input:{status:'clarify',message:'Какие слова?',options:[],task:null}}]})});assert.match(r.answer.message,/ссылка на объект размещения/);assert.equal(r.prepared,null);});
test('Travel pages contain concrete offers, correct breadcrumbs and preserved trip context',()=>{const html=travelPage();assert.equal(travelProducts.length,5);for(const p of travelProducts){assert.ok(html.includes('#product/'+p.id));const page=amazonPage({product:p,plan:{...plan(p.id),title:'Поиск',travel,columns:['Объект']}});assert.ok(page.includes('href="#travel">Travel /'));assert.ok(page.includes('2099-11-10'));assert.ok(!page.includes(' GLOBAL'));}assert.doesNotMatch(html,/Bright Data|Apify|gd_/);});
test('Travel workspace is persisted separately from another platform',async()=>{const docs=new Map();const fetcher=async(url,opt)=>{if(String(url).includes('/scrapers'))return Response.json(inventory('booking').inventory);const b=JSON.parse(opt.body);const prev=docs.get(b.capability)||{revision:0,document:null};if(b.document){assert.equal(prev.revision,b.expected_revision);docs.set(b.capability,{revision:prev.revision+1,document:b.document});}return Response.json(docs.get(b.capability)||prev);};async function call(path,data,cookie=''){const req=Readable.from(data?[Buffer.from(JSON.stringify(data))]:[]);req.method=data?'POST':'GET';req.url='/api/commerce/'+path;req.headers={origin:env.PUBLIC_ORIGIN,'content-type':'application/json','x-affsiwen-request':'1',cookie};const res={headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},end(v){this.data=JSON.parse(v);}};await createCloudHandler({env,fetcher})(req,res);return res;}const r=await call('booking/prepare',{...plan('booking'),task:'search',value:'Barcelona',travel});assert.equal(r.statusCode,200);const cookie=r.headers['set-cookie'][0].split(';')[0];assert.match(cookie,/aff_commerce_booking/);assert.equal((await call('booking/workspace',null,cookie)).data.plan.travel.adults,2);assert.equal((await call('airbnb/workspace',null,cookie)).data.plan,null);});

test('Travel result storage remains bounded for large Unicode values and URLs',()=>{const a=travelAdapter('booking'),p={...a.prepare(plan('booking'),inventory('booking')).display,limit:10};const row={hotel_name:'😀'.repeat(10000),address:'\\'.repeat(10000),rating:'x'.repeat(10000),price:'x'.repeat(10000),currency:'x'.repeat(10000),price_basis:'x'.repeat(10000),url:urls.booking+'?x='+'x'.repeat(10000)};const r=a.normalize(Array.from({length:10},()=>row),p);assert.ok(Buffer.byteLength(JSON.stringify(r))<40000);assert.equal(r.rows[0]['Ссылка'],'—');});
